prefix gist: <https://ontologies.semanticarts.com/gist/>

DELETE {
    ?ref ?refProp ?oldClass .
    ?oldClass ?defProp ?defObj .
}
INSERT {
    ?ref ?refProp ?newClass .
    ?newClass ?defProp ?defObj .
}
where {
    values (?oldClass ?newClass) {
        # Issue #434
        (gist:MimeType gist:MediaType)
        # Issue #483
        (gist:BuildingAddress gist:StreetAddress)
    }
    {
        ?ref ?refProp ?oldClass
    } UNION {
        ?oldClass ?defProp ?defObj
    }
}
