prefix gist: <https://ontologies.semanticarts.com/gist/>

DELETE {
    ?oldTerm ?sp ?so .
    ?ps ?oldTerm ?po .
    ?os ?op ?oldTerm .
}
INSERT {
    ?newTerm ?sp ?so .
    ?ps ?newTerm ?po .
    ?os ?op ?newTerm .
}
WHERE {
  VALUES (?oldTerm ?newTerm) {
    (gist:TaskExecution gist:Task)
    (gist:ScheduledTaskExecution gist:ScheduledTask)
    (gist:ProjectExecution gist:Project)
    (gist:PlannedEvent gist:ScheduledEvent)
  }
  {
      ?oldTerm ?sp ?so
  } UNION {
      ?ps ?oldTerm ?po
  } UNION {
      ?os ?op ?oldTerm
  }
}
