DELETE {
  ?s ?p ?o
}
INSERT {
  ?newS ?p ?o
}
WHERE {
  ?s ?p ?o 
  FILTER(STRSTARTS(STR(?s), "https://ontologies.semanticarts.com/gist/"))
  BIND(IRI(CONCAT("https://w3id.org/semanticarts/ns/ontology/gist/", REPLACE(STR(?s), "^.*[/#]", "")))AS ?newS)
}
