DELETE {
  ?s ?p ?o
}
INSERT {
  ?s ?newP ?o
}
WHERE {
  ?s ?p ?o 
  FILTER(STRSTARTS(STR(?p), "https://ontologies.semanticarts.com/gist/"))
  BIND(IRI(CONCAT("https://w3id.org/semanticarts/ns/ontology/gist/", REPLACE(STR(?p), "^.*[/#]", "")))AS ?newP)
}
