DELETE {
  GRAPH ?g {
    ?s ?p ?o
  }
}
INSERT {
  GRAPH ?g {
    ?s ?p ?newO
  }
}
WHERE {
  GRAPH ?g {
    ?s ?p ?o 
    FILTER(STRSTARTS(STR(?o), "https://ontologies.semanticarts.com/gist/"))
    BIND(IRI(CONCAT("https://w3id.org/semanticarts/ns/ontology/gist/", REPLACE(STR(?o), "^.*[/#]", "")))AS ?newO)
  }
}
