#!/usr/bin/env sh

# This file performs all the actual git pre-commit checks.
# It should be called by .git/hooks/pre-commit, which should be a copy of tools/pre-commit-hook.
# This is a test

# Stops accidental commits to branches master, main, or develop.
BRANCH=`git rev-parse --abbrev-ref HEAD`

if { [ "$BRANCH" = "develop" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "main" ]; }
then
  >&2 echo "You are on branch $BRANCH. You should not commit to this branch directly!"
  exit 1
fi

# Get absolute path to this script
# SCRIPT=$(readlink -f "$0")
# SCRIPTPATH=$(dirname "$SCRIPT")

# Get root directory of this git repository
base_dir=$(git rev-parse --show-toplevel)

# Restore executable bit in Git's index for files marked in .gitattributes.
# This is needed because Windows does not preserve the executable bit when files are edited.
git ls-files | git check-attr executable --stdin | grep ": executable: set$" | cut -d: -f1 | while read file; do
  current_mode=$(git ls-files --stage "$file" | cut -d' ' -f1)
  if [ "$current_mode" = "100644" ]; then
    git update-index --chmod=+x "$file"
  fi
done

# Run the serializer
set -x

"${base_dir}/tools/serializer/pre-commit"

rc=$?
set +x

# echo "RESULT == ${rc}"
if [ ! ${rc} -eq 0 ] ; then
  exit 1
fi

exit 0
