#!/usr/bin/env sh

# This file performs all the actual git pre-commit checks.
# It should be called by .git/hooks/pre-commit, which should be a copy of tools/pre-commit-hook.

# Get root directory of this git repository
base_dir=$(git rev-parse --show-toplevel)

# Stops accidental commits to branches master, main, or develop.
BRANCH=`git rev-parse --abbrev-ref HEAD`

if { [ "$BRANCH" = "develop" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "main" ]; }
then
  >&2 echo "You are on branch $BRANCH. You should not commit to this branch directly!"
  exit 1
fi

# We want to run a couple of scripts against the files that will be committed.
# They may change the files, this causes problems with git if you have additional
# changes in your working directory for the same files that are in the commit.

# Restore executable bit in Git's index for files marked in .gitattributes.
# This is needed because Windows does not preserve the executable bit when files are edited.
git ls-files | git check-attr executable --stdin | grep ": executable: set$" | cut -d: -f1 | while read file; do
  current_mode=$(git ls-files --stage "$file" | cut -d' ' -f1)
  if [ "$current_mode" = "100644" ]; then
    git update-index --chmod=+x "$file"
  fi
done

# Run the serializer
"${base_dir}/tools/serializer/pre-commit"
rc=$?
if [ ! ${rc} -eq 0 ] ; then
  echo "FAILURE: serializer; RESULT == ${rc}"
  exit 1
fi

# Remove any default PREFIX statements in the ontology files
"${base_dir}/tools/remove_default_prefix/remove_default_prefix.py"
rc=$?
if [ ! ${rc} -eq 0 ] ; then
  echo "FAILURE: remove_default_prefix.py; RESULT == ${rc}"
  exit 1
fi

exit 0

