#!/usr/bin/env sh

# this is expected to be in the .git/hooks directory of the project

# Stops accidental commits to branches master, main, or develop.
BRANCH=`git rev-parse --abbrev-ref HEAD`

if { [ "$BRANCH" = "develop" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "main" ]; }
then
  >&2 echo "You are on branch $BRANCH. You should not commit to this branch directly!"
  exit 1
fi

# Get absolute path to this script
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# Run the serializer
$SCRIPTPATH/../../tools/serializer/pre-commit
