#!/usr/bin/env sh

# This file performs all the actual git pre-commit checks.
# It should be called by .git/hooks/pre-commit, which should be a copy of tools/pre-commit-hook.

# Get absolute path to this script
# SCRIPT=$(readlink -f "$0")
# SCRIPTPATH=$(dirname "$SCRIPT")

# Get root directory of this git repository
base_dir=$(git rev-parse --show-toplevel)

# Stops accidental commits to branches master, main, or develop.
BRANCH=`git rev-parse --abbrev-ref HEAD`

if { [ "$BRANCH" = "develop" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "main" ]; }
then
  >&2 echo "You are on branch $BRANCH. You should not commit to this branch directly!"
  exit 1
fi

# We want to run a couple of scripts against the files that will be committed.
# They may change the files, this causes problems with git if you have additional
# changes in your working director for the same files that are in the commit.

# Run the serializer
"${base_dir}/tools/serializer/pre-commit"
rc=$?
if [ ! ${rc} -eq 0 ] ; then
  echo "FAILURE: serializer; RESULT == ${rc}"
  exit 1
fi

# Remove any default PREFIX statements in the ontology files
"${base_dir}/tools/remove_default_prefix/remove_default_prefix.py"
rc=$?
if [ ! ${rc} -eq 0 ] ; then
  echo "FAILURE: remove_default_prefix.py; RESULT == ${rc}"
  exit 1
fi

exit 0

