#!/usr/bin/env sh

# This file should be copied into the .git/hooks directory of the project.

# Stops accidental commits to branches master, main, or develop.
BRANCH=`git rev-parse --abbrev-ref HEAD`

if { [ "$BRANCH" = "develop" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "main" ]; }
then
  >&2 echo "You are on branch $BRANCH. You should not commit to this branch directly!"
  exit 1
fi

# Get absolute path to this script
# SCRIPT=$(readlink -f "$0")
# SCRIPTPATH=$(dirname "$SCRIPT")

# Get root directory of this git repository
base_dir=$(git rev-parse --show-toplevel)

# Run the serializer
set -x

"${base_dir}/tools/serializer/pre-commit"

rc=$?
set +x

# echo "RESULT == ${rc}"
if [ ! ${rc} -eq 0 ] ; then
  exit 1
fi

exit 0
