prefix sh: <http://www.w3.org/ns/shacl#>
prefix gist: <https://ontologies.semanticarts.com/gist/>
prefix newGist: <https://w3id.org/semanticarts/gist/>

DELETE {
    ?s ?p ?o
}
INSERT {
    ?newS ?p ?o
}
WHERE {
    {
        ?s ?p ?o 
        FILTER(STRSTARTS(STR(?s), "https://ontologies.semanticarts.com/gist/"))
        BIND(IRI(CONCAT("https://w3id.org/semanticarts/gist/", REPLACE(STR(?s), '^.*[/#]')AS ?newS)
    }
}
;
DELETE {
    ?s ?p ?o
}
INSERT {
    ?s ?newP ?o
}
WHERE {
    {
        ?s ?p ?o 
        FILTER(STRSTARTS(STR(?p), "https://ontologies.semanticarts.com/gist/"))
        BIND(IRI(CONCAT("https://w3id.org/semanticarts/gist/", REPLACE(STR(?p), '^.*[/#]')AS ?newP)
    }
}
;
DELETE {
    ?s ?p ?o
}
INSERT {
    ?s ?p ?newO
}
WHERE {
    {
        ?s ?p ?o 
        FILTER(STRSTARTS(STR(?o), "https://ontologies.semanticarts.com/gist/"))
        BIND(IRI(CONCAT("https://w3id.org/semanticarts/gist/", REPLACE(STR(?o), '^.*[/#]')AS ?newO)
    }
}
