prefix gist: <https://ontologies.semanticarts.com/gist/>
prefix newGist: <https://w3id.org/semanticarts/gist/>

DELETE {
    graph ?g {
        ?s ?p ?percentage ;
        ?percentage ?predicate ?object ;
    }
}
INSERT {
    graph ?g {
        ?s ?p ?magnitude .
        ?magnitude newGist:hasUnitOfMeasure newGist:_percent ;
            newGist:numericValue ?value ;
        .
    }
}
where {
    graph ?g {
        ?s ?p ?percentage .
        ?percentage rdf:type gist:Percentage ;
            gist:numericValue ?value ;
            ?predicate ?object ;
        .
    }
    BIND(IRI(CONCAT(gist:Magnitude , STRUUID()))AS ?magnitude)
}
