prefix gist: <https://ontologies.semanticarts.com/gist/>

DELETE {
    ?ref ?refProp ?oldClass .
    ?oldClass ?defProp ?defObj .
}
INSERT {
    ?ref ?refProp ?newClass .
    ?newClass ?defProp ?defObj .
}
where {
    values (?oldClass ?newClass) {
        (gist:ContemporaneousEvent gist:ContemporaryEvent)
    }
    {
        ?ref ?refProp ?oldClass
    } UNION {
        ?oldClass ?defProp ?defObj
    }
}
