prefix gist: <https://ontologies.semanticarts.com/gist/>

DELETE {
    graph ?graph {
        ?ref ?refProp ?oldClass .
        ?oldClass ?defProp ?defObj .
    }
}
INSERT {
    graph ?graph {
        ?ref ?refProp ?newClass .
        ?newClass ?defProp ?defObj .
    }
}
where {
    values (?oldClass ?newClass) {
        (gist:ContemporaneousEvent gist:ContemporaryEvent)
    }
    graph ?graph {
        {
            ?ref ?refProp ?oldClass
        } UNION {
            ?oldClass ?defProp ?defObj
        }
    }
}
