# find subclasses of Unit of Measure
# 
# use the output to customize the values list of removeSubclassesOfUnitOfMeasure

select distinct ?subclass

where {

    ?subclass  (rdfs:subClassOf|(owl:equivalentClass/owl:intersectionOf/rdf:first))+ gist:UnitOfMeasure .

}
order by ?subclass 

