# find subclasses of Magnitude that represent Aspects
# note: the subclass ReferenceValue does not represent an Aspect
# 
# use the output to customize the values list of removeSubclassesOfMagnitude 

select distinct ?subclass

where {

    ?subclass  (rdfs:subClassOf|(owl:equivalentClass/owl:intersectionOf/rdf:first))+ gist:Magnitude .
    filter(?subclass != gist:ReferenceValue)

}
order by ?subclass 
