# show existing Aspect/UnitOfMeasure pairs
# these pairs will be candidates for updating the Semantic Arts reference data
#
# copy the values statements from the lower section (filter not exists) of findAspects2


select distinct  ?aspect  ?unit

where {
  
   ?magnitude gist:hasUnitOfMeasure ?unit .

   ?thing gist:hasMagnitude ?magnitude ;
          ?thingProperty ?thingPropertyValue ;
          .
                
   {
    ################ copy from findAspects2 #################
    values ?thingPropertyValue { 

           }
           ##################################################

    bind(?thingPropertyValue as ?aspect)
   }

   union
   {
    ################ copy from findAspects2 #################
     values ?thingProperty  { 

            }
           ##################################################

    bind(?thingProperty as ?aspect)
   }

}
order by ?aspect ?unit

