# show existing Aspect/UnitOfMeasure pairs based on findAspects1
# these pairs will be candidates for updating the Semantic Arts reference data
#
# copy the values statements from the lower section (filter not exists) of findAspects1

select distinct ?aspect ?unit

where {
  
   ?magnitude gist:hasUnitOfMeasure ?unit ;
              ?magnitudeProperty ?magnitudePropertyValue  ;
              .
              
   {
    ################ copy from findAspects1 #################
    values ?magnitudePropertyValue  {
       
           }

           ##################################################

    bind(?magnitudePropertyValue as ?aspect)
   }

   union
   {
    ################ copy from findAspects1 #################
    values ?magnitudeProperty {

           }
           ##################################################

    bind(?magnitudeProperty as ?aspect)
   }

}
order by ?aspect ?unit
