# show Aspect/UnitOfMeasure pairs where the Aspect is represented as a property with a Magnitude as object
# these pairs will be candidates for updating the Semantic Arts reference data
#

select distinct ?thingToMagnitudeProperty ?unit 

where {
  
  ?magnitude gist:hasUnitOfMeasure ?unit .
  
  ?thing ?thingToMagnitudeProperty ?magnitude .


    ################ copy from findAspects3 #################
    values ?thingToMagnitudeProperty {

           }
           ##################################################
  } order by ?thingToMagnitudeProperty ?unit
