# use the property hasMagnitude to relate a thing to a magnitude
# use the output of findAspects3 to identify the thing/magnitude pairs of interest

# test
construct {?thing ?thingToMagnitudProperty ?magnitude.}

# update graph
# insert {graph ?g {?thing gist:hasMagnitude ?magnitude .}}

where {

  values ?thingToMagnitudeProperty  {
#        ex:hasArea    # sample value, commented out
         }
 
  ?magnitude gist:hasUnitOfMeasure ?unit .

  graph ?g {
        ?thing ?thingToMagnitudeProperty ?magnitude.
        filter not exists {?thing gist:hasMagnitude ?magnitude.} 
        }
  }

