# use gist:offers in named graphs to relate an offer to the thing being offered
# in this script, gist:offers will replace gist:isPartOf
# be sure all instances returned by test relate an offer to the THING OFFERED

# test
select ?g ?offer ?thingOffered 

# update graph

# delete {graph ?g {?thingOffered gist:isPartOf ?offer .}} 

# insert {graph ?g {?offer gist:offers  ?thingOffered .}} 

where {

# triples in named graphs that relate an offer to the thing offered
# filters out "sub-offers"

  {graph ?g {

         ?offer rdf:type/rdfs:subClassOf* gist:Offer .

         ?offerPart gist:isPartOf ?offer .

         filter not exists {?offerPart rdf:type/rdfs:subClassOf* gist:Offer .}

         bind(?offerPart as ?thingOffered)
         }}
}
